"""add_agent_support

Revision ID: 4e75adccff01
Revises: 72da8749bcaa
Create Date: 2025-11-02 11:59:59.800350

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e75adccff01"
down_revision: str | Sequence[str] | None = "72da8749bcaa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sources", sa.Column("agent_type", sa.String(), nullable=True))
    op.add_column("sources", sa.Column("agent_config", sa.String(), nullable=True))
    op.add_column(
        "sources",
        sa.Column("agent_enabled", sa.Boolean(), nullable=False, server_default="0"),
    )
    op.create_table(
        "agent_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("queued_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_tasks")
    op.drop_column("sources", "agent_enabled")
    op.drop_column("sources", "agent_config")
    op.drop_column("sources", "agent_type")
    # ### end Alembic commands ###
