"""add_feed_key_to_users

Revision ID: 72da8749bcaa
Revises: 16516c3575c5
Create Date: 2025-11-01 15:37:08.083163

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72da8749bcaa"
down_revision: str | Sequence[str] | None = "16516c3575c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "feed_key",
            sa.String(32),
            nullable=False,
            server_default="00000000000000000000000000000000",
        ),
    )
    op.create_index(op.f("ix_users_feed_key"), "users", ["feed_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_feed_key"), table_name="users")
    op.drop_column("users", "feed_key")
    # ### end Alembic commands ###
