"""add_feed_key_to_users

Revision ID: 72da8749bcaa
Revises: 16516c3575c5
Create Date: 2025-11-01 15:37:08.083163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72da8749bcaa"
down_revision: Union[str, Sequence[str], None] = "16516c3575c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("feed_key", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_users_feed_key"), "users", ["feed_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_feed_key"), table_name="users")
    op.drop_column("users", "feed_key")
    # ### end Alembic commands ###
